[package]
name = "maptos-opt-executor"
description = "Executor for the AptosVM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
fail = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
schemars = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
hex = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
derive_more = { workspace = true, default-features = true }
lazy_static = "1.4.0"
tokio = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
async-channel = { workspace = true }
tonic = { wrkspace = true }

aptos-vm = { workspace = true }
aptos-vm-validator = { workspace = true }
aptos-config = { workspace = true }
aptos-sdk = { workspace = true }
aptos-crypto = { workspace = true }
aptos-consensus-types = { workspace = true }
aptos-db = { workspace = true }
aptos-api = { workspace = true }
aptos-api-types = { workspace = true }
aptos-types = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-block-executor = { workspace = true }
aptos-vm-types = { workspace = true }
aptos-vm-logging = { workspace = true }
aptos-vm-genesis = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
aptos-framework = { workspace = true }
aptos-executor = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-executor-test-helpers = { workspace = true }
aptos-bitvec = { workspace = true }
aptos-mempool = { workspace = true }
aptos-temppath = { workspace = true }
aptos-faucet-core = { workspace = true }
aptos-cached-packages = { workspace = true }
maptos-execution-util = { workspace = true }
movement-types = { workspace = true }
aptos-indexer-grpc-fullnode = { workspace = true }
aptos-indexer-grpc-table-info = { workspace = true }
aptos-indexer = { workspace = true }
aptos-protos = { workspace = true }
dirs = { workspace = true }
tempfile = { workspace = true }
tracing-test = { workspace = true }
async-trait = { workspace = true }

# optional logging dependencies
tracing-subscriber = { workspace = true, optional = true }

[features]
default = ["logging"]
logging = ["tracing-subscriber"]
