[package]
name = "movement-tracing"
description = "Tracing utilities with timing support for Movement services"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
#console-subscriber = { workspace = true }

[lints]
workspace = true
