version: "3.8"

services:
  
  movement-backup-db:
    image: ghcr.io/movementlabsxyz/movement-full-node:${CONTAINER_REV}
    container_name: movement-backup-db
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - MOVEMENT_TIMING=info
      - SUZUKA_TIMING_LOG=/.movement/movement-timing.log
      - RUST_BACKTRACE=1
      - AWS_REGION=us-west-1
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - SYNC_PATTERN=${SYNC_PATTERN}
      - SYNC_BUCKET=${SYNC_BUCKET}
      - SYNC_ARCHIVE=${SYNC_BUCKET}
    command: backup save-and-push $SYNC_BUCKET $SYNC_PATTERN $SYNC_ARCHIVE 
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
