[package]
name = "maptos-framework-release-util"
description = "Executor for the AptosVM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
aptos-sdk = { workspace = true }
aptos-framework = { workspace = true }
aptos-cached-packages = { workspace = true }
thiserror = { workspace = true }
aptos-release-builder = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
movement = { workspace = true }
move-package = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
aptos-types = { workspace = true }
tracing = { workspace = true }
aptos-db = { workspace = true }
aptos-storage-interface = { workspace = true }

[[bin]]
name = "onchain_execution_config"
path = "src/onchain_execution_config.rs"