[package]
name = "ethereum-bridge"
description = "bridge components for the ethereum bridge"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
dashmap = { workspace = true }
delegate = { workspace = true }
poem = { workspace = true }
hex = { workspace = true }
keccak-hash = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
# This can be moved to a shared lib
rand_chacha = "0.2.2"
rand = { workspace = true }
thiserror = { workspace = true }

alloy = { workspace = true, features = [
  "full",
  "rpc",
  "rpc-types",
  "serde",
  "rlp",
  "contract",
  "sol-types",
] }
alloy-rlp.workspace = true

bridge-shared = { workspace = true }
serde_with.workspace = true
url = { workspace = true, features = ["serde"] }

#To be removed after send_transaction refactor
mcr-settlement-client = { workspace = true }
