[package]
name = "hashicorp-vault-signer"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
vaultrs = { workspace = true }
anyhow = { workspace = true }
aws-sdk-kms = { workspace = true }
aws-config = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
dotenv = "0.15"
ed25519 = { workspace = true }
ring-compat = { workspace = true }
k256 = { workspace = true, features = ["ecdsa", "pkcs8"] }
google-cloud-kms = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { workspace = true }
signer = { workspace = true }

[lints]
workspace = true