[package]
name = "host"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true } 
risc0-zkvm = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true } 

methods = { path = "../methods" }




