services:

  setup:
    image: busybox
    container_name: setup
    command: sh -c 'echo "No setup type specified."'
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  celestia-light-node:
    image: busybox
    container_name: celestia-light-node
    command: sh -c 'echo "No setup type specified."'
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - CELESTIA_RPC_ADDRESS=celestia-light-node:26657
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s

  celestia-light-node-synced:
    image: ghcr.io/movementlabsxyz/wait-for-celestia-light-node:${CONTAINER_REV}
    container_name: celestia-light-node-synced
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      celestia-light-node:
        condition: service_healthy

  m1-da-light-node:
    image: ghcr.io/movementlabsxyz/m1-da-light-node:${CONTAINER_REV}
    container_name: m1-da-light-node
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      celestia-light-node-synced:
        condition: service_completed_successfully
    ports:
      - "30730:30730"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 30730" ]
      retries: 10
      interval: 10s
      timeout: 5s

  suzuka-full-node:
    image: ghcr.io/movementlabsxyz/suzuka-full-node:${CONTAINER_REV}
    container_name: suzuka-full-node
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      - m1-da-light-node
    ports:
      - "30731:30731"
      - "30734:30734"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 30731" ]
      retries: 10
      interval: 10s
      timeout: 5s

  suzuka-faucet-service:
    image: ghcr.io/movementlabsxyz/suzuka-faucet-service:${CONTAINER_REV}
    container_name: suzuka-faucet-service
    command: run-simple
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    ports:
      - "30732:30732"
    depends_on:
      suzuka-full-node:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 30732" ]
      retries: 10
      interval: 10s
      timeout: 5s

volumes:
  dot-movement:

