[package]
name = "aptos-framework-known-release"
description = "Executor for the AptosVM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
maptos-framework-release-util = { workspace = true }
aptos-framework-elsa-release = { workspace = true }
aptos-framework-biarritz-rc1-release = { workspace = true }
aptos-framework-pre-l1-merge-release = { workspace = true }
aptos-framework-head-release = { workspace = true }
aptos-framework = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true}
thiserror = { workspace = true}