[package]
name = "bridge-setup"
description = "Setting up of bridge configuration"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
bridge-config = { workspace = true }
bridge-service = { workspace = true }
dot-movement = { workspace = true }
commander = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
k256 = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
godfig = { workspace = true }
hex = { workspace = true }

aptos-sdk = { workspace = true }


[lints]
#workspace = true
