---
- name: Install requirements and the Movement Node
  hosts: all
  become: true
  remote_user: "{{ user }}"
  gather_facts: false
  vars:
    repo_url: "https://github.com/movementlabsxyz/movement"
    destination_path: "/home/{{ user }}/movement"
    rev: "{{ movement_container_version }}"

  tasks:
    - debug:
        msg: "MOVEMENT_SYNC: {{ movement_sync }}"

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - xz-utils
          - git
          - nginx
          - python3-pip
        state: present
        update_cache: yes

    - name: Clone the appropriate application version
      git:
        repo: "{{ repo_url }}"
        dest: "{{ destination_path }}"
        version: "{{ movement_container_version }}"
        clone: yes
        update: yes
        force: true
      become: no  # Run git clone as the ansible user or specify a different user

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | bash

    - name: Enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      ansible.builtin.shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

    - name: Install OpenSSL and CA certificates
      ansible.builtin.package:
        name:
          - openssl
          - ca-certificates
        state: present

    - name: Update CA certificates
      ansible.builtin.shell: update-ca-certificates

    - name: Create movement env file and add the container version
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/movement/.env"
        line: "REV={{ movement_container_version }}"
        create: yes

    - name: Make sure that the movement config dir exists 
      ansible.builtin.file:
        path: "/home/{{ user }}/.movement"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Create movement-full-node systemd service
      ansible.builtin.template:
        src: "./movement-full-follower.service.j2"
        dest: /etc/systemd/system/movement-full-follower.service

    - name: Stop the movement-full-node service if running
      ansible.builtin.systemd:
        name: movement-full-follower
        state: stopped
        enabled: no

    - name: Reload systemd to apply changes
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable and start the movement-full-node service
      ansible.builtin.systemd:
        name: movement-full-follower
        enabled: yes
        state: started

