[package]
name = "movement-types"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aptos-types = { workspace = true }
bcs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
# derivative = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
