[package]
name = "bridge-integration-tests"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
aptos-framework = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
aptos-logger = { workspace = true }
aptos-types = { workspace = true }
aptos-sdk = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
alloy = { workspace = true }
reqwest = { workspace = true }
alloy-network = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-contract = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
futures = { workspace = true }
tiny-keccak = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

bridge-service = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
