[package]
name = "movement-bridge"
description = "bridge components for the Movement Atomic Bridge"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
async-stream = { workspace = true }
aptos-sdk = { workspace = true }
aptos-types = { workspace = true }
aptos-api = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }
derive-new = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
poem = { workspace = true }
keccak-hash = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rand_chacha = "0.2.2"
rand = { workspace = true }

url = { workspace = true }
once_cell = { workspace = true }

bridge-shared = { workspace = true }
