[package]
name = "bridge-config"
description = "Configuration of the Bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true , features = ["derive"] }
alloy = { workspace = true }
aptos-sdk = { workspace = true }
dot-movement = { workspace = true }
godfig = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true