[package]
name = "m1-da-light-node-util"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "wait-for-celestia-light-node"
path = "src/bin/wait_for_light_node.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
m1-da-light-node-grpc = { workspace = true, features = [] }
celestia-rpc = { workspace = true }
celestia-types = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
async-stream = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
jsonrpsee = { workspace = true }
dot-movement = { workspace = true }
toml = { workspace = true }
memseq-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
godfig = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
