[package]
name = "suzuka-config"
description = "Config tool for Suzuka"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
maptos-execution-util = { workspace = true }
mcr-settlement-config = { workspace = true }
mcr-settlement-client = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
m1-da-light-node-util = { workspace = true }
godfig = { workspace = true }
syncup = { workspace = true }
movement-types = { workspace = true }
dot-movement = { workspace = true }