[package]
name = "suzuka-config"
description = "Config tool for Suzuka"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "suzuka-config"
path = "src/bin/suzuka_config.rs"

[dependencies]
movement-execution-util = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }