[package]
name = "syncador"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
flocks = { workspace = true }
async-stream = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
aws-types = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
movement-types = { workspace = true }
async-trait = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
clap = { workspace = true }
globset = { workspace = true }
glob = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
