[package]
name = "memseq"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mempool-util = { workspace = true }
sequencing-util = { workspace = true }
tokio = { workspace = true }
movement-types = { workspace = true }
anyhow = { workspace = true }
move-rocks = { workspace = true }
tempfile = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true
