[package]
name = "movement-da-sequencer-setup"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[[bin]]
name = "movement-da-replica-setup"
path = "bin/replicat_setup.rs"

[dependencies]
dot-movement = { workspace = true }
godfig = { workspace = true }
movement-da-sequencer-config = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }

maptos-execution-util = { workspace = true }
movement-signer = { workspace = true }
movement-signer-loader = { workspace = true }
movement-da-sequencer-node = { workspace = true }

[lints]
workspace = true
