name: M2 CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential lld libpq-dev unzip
          sudo apt install -y pkg-config libusb-1.0-0-dev libftdi1-dev
          sudo apt-get install libudev-dev libdw1 libdw-dev 

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          components: rustfmt, clippy
          override: true

      - name: cargo check
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          export RUSTUP_HOME=$HOME/.rustup
          export CARGO_HOME=$HOME/.cargo
          export PATH=$CARGO_HOME/bin:$PATH
          cargo check --verbose

      - name: cargo test
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          export RUSTUP_HOME=$HOME/.rustup
          export CARGO_HOME=$HOME/.cargo
          export PATH=$CARGO_HOME/bin:$PATH
          cargo test --verbose
